export enum ProviderNames {
  POSTGRES_DATABASE = "POSTGRES_DATABASE",
  // REPOSITORIES
  USER_REPOSITORY = "USER_REPOSITORY",
  MOVIE_REPOSITORY = "MOVIE_REPOSITORY",
  SESSION_REPOSITORY = "SESSION_REPOSITORY",
  TICKET_REPOSITORY = "TICKET_REPOSITORY",
  WATCH_MOVIE_REPOSITORY = "WATCH_MOVIE_REPOSITORY",

  // SERVICES
  USER_SERVICE = "USER_SERVICE",
  MOVIE_SERVICE = "MOVIE_SERVICE",
  SESSION_SERVICE = "SESSION_SERVICE",
  TICKET_SERVICE = "TICKET_SERVICE",
  WATCH_MOVIE_SERVICE = "WATCH_MOVIE_SERVICE",
  AUTH_SERVICE = "AUTH_SERVICE",

  // CONVERTERS
  USER_CONVERTER = "USER_CONVERTER",
  MOVIE_CONVERTER = "MOVIE_CONVERTER",
  SESSION_CONVERTER = "SESSION_CONVERTER",
  TICKET_CONVERTER = "TICKET_CONVERTER",
}